# Generated by Django 6.0.1 on 2026-02-10 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pollster",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_manager", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Respondent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname_1", models.CharField(max_length=100)),
                ("fname_2", models.CharField(blank=True, default=None, max_length=100)),
                ("lname_1", models.CharField(max_length=100)),
                ("lname_2", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("is_alive", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_creation", models.DateField()),
                ("survey_name", models.CharField(max_length=80)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="surveys.pollster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                (
                    "answer_type",
                    models.IntegerField(
                        choices=[
                            (0, "Text"),
                            (1, "Number"),
                            (2, "Date"),
                            (3, "Categorical"),
                        ]
                    ),
                ),
                ("survey", models.ManyToManyField(default=None, to="surveys.survey")),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_creation", models.DateField()),
                ("answer_text", models.CharField(max_length=100)),
                (
                    "pollster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="surveys.pollster",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.question",
                    ),
                ),
                (
                    "respondent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.respondent",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surveys.survey"
                    ),
                ),
            ],
        ),
    ]
