# Generated by Django 6.0.1 on 2026-02-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="date_of_creation",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.IntegerField(
                choices=[(0, "text"), (1, "number"), (2, "date"), (3, "checkbox")]
            ),
        ),
    ]
