# Generated by Django 6.0.1 on 2026-02-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_alter_answer_date_of_creation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="date_of_creation",
            field=models.DateField(auto_now_add=True),
        ),
    ]
